default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sammy
  password: onepiece


development:
  <<: *default
  database: book_lending_library_development

test:
  <<: *default
  database: book_lending_library_test


production:
  primary: &primary_production
    <<: *default
    database: book_lending_library_production
    username: book_lending_library
    password: <%= ENV["BOOK_LENDING_LIBRARY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: book_lending_library_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: book_lending_library_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: book_lending_library_production_cable
    migrations_paths: db/cable_migrate
